# Generated by Django 5.0.6 on 2025-01-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField(default=0.0, help_text='total distance traveled in kilomeeters')),
                ('total_emissions', models.FloatField(default=0.0, help_text='total co2 emissions ')),
            ],
        ),
        migrations.CreateModel(
            name='Transportationmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('bus', 'Bus'), ('scooter', 'Scooter')], max_length=50)),
                ('distance', models.FloatField(help_text='Distance travelled in kilomeeters')),
                ('mode', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=50)),
                ('vehicle_size', models.CharField(choices=[('small', 'Small'), ('average', 'Average'), ('large', 'Large'), ('big', 'Big')], help_text='Size category of the vehicle', max_length=50)),
                ('emissions', models.FloatField(help_text='Co2 emmissions in grams ')),
            ],
        ),
    ]
