# Generated by Django 5.0.6 on 2025-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionssummary',
            name='total_distance',
            field=models.FloatField(default=0.0, help_text='Total distance traveled in kilometers'),
        ),
        migrations.AlterField(
            model_name='emissionssummary',
            name='total_emissions',
            field=models.FloatField(default=0.0, help_text='Total CO₂ emissions in grams'),
        ),
        migrations.AlterField(
            model_name='transportationmodel',
            name='distance',
            field=models.FloatField(help_text='Distance travelled in kilometers'),
        ),
        migrations.AlterField(
            model_name='transportationmodel',
            name='emissions',
            field=models.FloatField(blank=True, help_text='CO₂ emissions in grams', null=True),
        ),
    ]
