# Generated by Django 5.0.6 on 2025-01-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_emissionssummary_total_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionssummary',
            name='total_distance',
        ),
        migrations.AddField(
            model_name='emissionssummary',
            name='average_emissions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='emissionssummary',
            name='total_emissions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transportationmodel',
            name='vehicle_size',
            field=models.CharField(choices=[('small', 'Small'), ('average', 'Average'), ('large', 'Large'), ('big', 'Big')], max_length=50),
        ),
    ]
